format = """
$python\
$kubernetes\
$directory\
$git_branch\
$git_status\
$git_state\
$custom\
$cmd_duration\
$line_break\
$env_var.VI_MODE\
$shell\
$character"""

[python]
format = '[(\($symbol$virtualenv $version\) )]($style)'

[kubernetes]
disabled = false

[env_var.VI_MODE]
disabled = false
variable = "ZSH_VI_MODE"
default = "TACO"
